name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
  - name: Deploy

  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v5

    - name: Build app
      run: scripts/buildprod.sh
